# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-30 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_activity_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('F', 'Favorite'), ('L', 'Like'), ('U', 'Up Vote'), ('D', 'Down Vote')], max_length=1),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('L', 'Liked'), ('F', 'Favorited'), ('A', 'Answered'), ('W', 'Accepted Answer')], max_length=1),
        ),
    ]
