# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-30 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_moviespider_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='full/'),
        ),
    ]
